// <auto-generated />
using System;
using EMG_MED1000_BACKEND.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMG_Med1000_backend.Migrations
{
    [DbContext(typeof(VoitureContext))]
    [Migration("20260501170039_InitialVoitureDb")]
    partial class InitialVoitureDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EMG_MED1000_BACKEND.Entities.Marque", b =>
                {
                    b.Property<int>("MarqueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MarqueId"));

                    b.Property<string>("NomMarque")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("MarqueId");

                    b.HasIndex("NomMarque")
                        .IsUnique();

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("EMG_MED1000_BACKEND.Entities.Modele", b =>
                {
                    b.Property<int>("ModeleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ModeleId"));

                    b.Property<DateTime>("AnneeModele")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("NomModele")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("ModeleId");

                    b.HasIndex("MarqueId");

                    b.HasIndex("NomModele")
                        .IsUnique();

                    b.ToTable("Modeles");
                });

            modelBuilder.Entity("EMG_MED1000_BACKEND.Entities.Voiture", b =>
                {
                    b.Property<int>("VoitureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VoitureId"));

                    b.Property<DateTime>("AnneeVoiture")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("MarqueId")
                        .HasColumnType("int");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("VoitureId");

                    b.HasIndex("MarqueId");

                    b.ToTable("Voitures");
                });

            modelBuilder.Entity("EMG_MED1000_BACKEND.Entities.Modele", b =>
                {
                    b.HasOne("EMG_MED1000_BACKEND.Entities.Marque", "Marque")
                        .WithMany("Modeles")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("EMG_MED1000_BACKEND.Entities.Voiture", b =>
                {
                    b.HasOne("EMG_MED1000_BACKEND.Entities.Marque", "Marque")
                        .WithMany()
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marque");
                });

            modelBuilder.Entity("EMG_MED1000_BACKEND.Entities.Marque", b =>
                {
                    b.Navigation("Modeles");
                });
#pragma warning restore 612, 618
        }
    }
}
